// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzQ33vng-LJoE9OVYa75pemupFrhhGK4I',
    appId: '1:1065436407901:web:0fb29940cf5f77328605b4',
    messagingSenderId: '1065436407901',
    projectId: 'x7healthcare',
    authDomain: 'x7healthcare.firebaseapp.com',
    storageBucket: 'x7healthcare.appspot.com',
    measurementId: 'G-MM5NWKM709',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGLt-sIgj0b0SlFNgGcF25M6BYCcW0Uno',
    appId: '1:1065436407901:android:60bd9f7931ff973a8605b4',
    messagingSenderId: '1065436407901',
    projectId: 'x7healthcare',
    storageBucket: 'x7healthcare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBahmlaNKdhJcfFxAJBtcGfNXWQJHQoxk4',
    appId: '1:1065436407901:ios:63c299a3a1f17d4d8605b4',
    messagingSenderId: '1065436407901',
    projectId: 'x7healthcare',
    storageBucket: 'x7healthcare.appspot.com',
    iosBundleId: 'com.example.rootalyTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBahmlaNKdhJcfFxAJBtcGfNXWQJHQoxk4',
    appId: '1:1065436407901:ios:63c299a3a1f17d4d8605b4',
    messagingSenderId: '1065436407901',
    projectId: 'x7healthcare',
    storageBucket: 'x7healthcare.appspot.com',
    iosBundleId: 'com.example.rootalyTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzQ33vng-LJoE9OVYa75pemupFrhhGK4I',
    appId: '1:1065436407901:web:12c47f5f4846b6da8605b4',
    messagingSenderId: '1065436407901',
    projectId: 'x7healthcare',
    authDomain: 'x7healthcare.firebaseapp.com',
    storageBucket: 'x7healthcare.appspot.com',
    measurementId: 'G-TSJPV526ZP',
  );
}
